import { AddressHunt, BasisForAddress, SpareRecipe, StaircaseBasis, TrimToBasis } from "@/components/interactive/basis";
import { BackToB, ChangeMatrixBuilder, RenameTheArrow, SimilarityHunt, TwoAddresses } from "@/components/interactive/change-of-basis";
import { CharacteristicSweep, EigenpairHunt, RepeatedRootSlider, TriangularPolyMatch } from "@/components/interactive/characteristic-equation";
import { CofactorHunt, CofactorLinePicker, ColumnClearExpand, MultipleAreaScale, ReplacementShear } from "@/components/interactive/cofactor-expansion";
import { ConsistencyLine, OutputReach, PivotPicker, RelationTwins, RowSlide } from "@/components/interactive/column-space";
import { CoordinateBuilder, CoordinateFinder, PolynomialCoordinates, SpanDimension } from "@/components/interactive/coordinates";
import { CramerAreas, CramerParameterLines, EllipseAreaStretch, HeightStack, ProductAreaHunt } from "@/components/interactive/determinant-properties";
import { AreaShearSlide, ColumnStretch, CornerToOrigin, SignSweep } from "@/components/interactive/determinants-as-area";
import { DiagonalEntryMatch, DiagonalFactorSteps, EigenColumnHunt, EigenCoordinateTarget } from "@/components/interactive/diagonalization";
import { BasisColumnBuilder, DiagonalBasisHunt, EigenOrbitSettle, EigenPolynomialHunt, TwoCoordinateMap } from "@/components/interactive/diagonalizing-transformations";
import { EigenWeightSplit, IterateSwing, PowerLineStretch, ShiftToSingular, TraceCurveMatch } from "@/components/interactive/eigenvalue-properties";
import { DiagonalZeroHunt, EigenCandidatePicker, EigenDirectionHunt, EigenGapHunt, EigenLineCollapse } from "@/components/interactive/eigenvectors";
import { BuildFromSteps, ElementaryMoves, InverseBuilder, RowRecipe } from "@/components/interactive/elementary";
import { ChainCoordinates, JordanChainBuilder, MultiplicityGapSlider, NullPowerClimb, ShearRaySweep } from "@/components/interactive/generalized-eigenvectors";
import { NormalizePair, QrWeightSliders, ShadowSubtractSlider, StraightenedTargetHunt, VanishingStepHunt } from "@/components/interactive/gram-schmidt";
import { ComplementLanding, RangeCollapse, RangeProbe, ThirdColumnBudget } from "@/components/interactive/image-range";
import { CollinearHunt, LiftToPlane, LoopAnywhere, RelationFinder, ZeroFunctionHunt } from "@/components/interactive/independence";
import { DotShadowHunt, EqualDistanceTurn, OrthogonalWeights, RowPerpendicularHunt, UnitCircleScale } from "@/components/interactive/inner-products";
import { DeterminantSlider, InverseColumnsHunt, SameLanding, SingularHunt, UndoOrder } from "@/components/interactive/inverse";
import { CrushAndMiss, InvertibilityCalls, StatementBoard, ThirdPivotSlider } from "@/components/interactive/invertible-matrix-theorem";
import { DifferenceInKernel, EvaluationKernel, SecondDerivativeTwins, ZeroLanding } from "@/components/interactive/kernel";
import { ParabolaFit, ProjectionRightAngle, ResidualBalance, ResidualSquaresFit } from "@/components/interactive/least-squares";
import { AdditivityHunt, DerivativeTarget, EvaluationZeros, SharedDerivativeHunt, TranslationGap } from "@/components/interactive/linear-maps";
import { CostCompare, LUBuilder, PivotFlattener, SubstitutionSolver, TwoTriangleSolve } from "@/components/interactive/lu";
import { ColumnSpanCheck, MatrixVectorExplorer, RowPictureSolver, SpanBreaker } from "@/components/interactive/matrix";
import { ColumnBuilder, DerivativeRoutes, LandingPredict, RotationColumns } from "@/components/interactive/matrix-representations";
import { FreeWeights, LandingHunt, NullSumCheck, RightSideShift } from "@/components/interactive/null-space";
import { LineFootHunt, LineOnlyShadow, NearestPlanePoint, ShadowPreimageHunt, ShadowSumBasis } from "@/components/interactive/orthogonal-projection";
import { ColumnWeights, CommuteHunt, CompositionExplorer, ProductColumns, ZeroProductHunt } from "@/components/interactive/product";
import { LevelPointHunt, NegativeDirectionHunt, QuadraticAxisTurner, QuadraticCircleMax, QuadraticSurfaceShaper } from "@/components/interactive/quadratic-forms";
import { CollapseSlider, PivotBudget, RankTally, RowColumnDrop } from "@/components/interactive/rank-nullity";
import { CollapsedDirectionHunt, LongestStretchHunt, PerpendicularPairHunt, RankCopyBudget, SvdEllipseMatch } from "@/components/interactive/singular-value-decomposition";
import { EntryHunt, LineSpanPicker, RowLinesMeet, SpanPainter } from "@/components/interactive/span";
import { ConsistencyHunt, GrowTheSpan, PivotHunt, PolynomialRecipe, ThirdVectorHunt } from "@/components/interactive/span-revisited";
import { CounterexampleHunt, PolynomialSetTest, QuadrantEscape, ShiftedLineTest } from "@/components/interactive/subspaces";
import { EigenDirectionSweep, ShadowStretchSum, SpectralEllipseBuilder, SymmetricPerpendicularHunt } from "@/components/interactive/symmetric-matrices";
import { PivotSpotter, RowReduceExplorer, RowReducer, SolutionCountExplorer } from "@/components/interactive/systems";
import { TransformExplorer } from "@/components/interactive/transform";
import { ImagePredictor, PreimageHunt, RotationDial, ShapeMatch } from "@/components/interactive/transformations";
import { ClosureHunt, NegativeFinder, PolynomialCombiner, ScalingEscape } from "@/components/interactive/vector-spaces";
import { AdditionExplorer, CombinationTarget, DifferenceExplorer, GridWeights, ScaleExplorer, VectorExplorer } from "@/components/interactive/vectors";

export const widgets = {
  AdditionExplorer,
  AdditivityHunt,
  AddressHunt,
  AreaShearSlide,
  BackToB,
  BasisColumnBuilder,
  BasisForAddress,
  BuildFromSteps,
  ChainCoordinates,
  ChangeMatrixBuilder,
  CharacteristicSweep,
  ClosureHunt,
  CofactorHunt,
  CofactorLinePicker,
  CollapseSlider,
  CollapsedDirectionHunt,
  CollinearHunt,
  ColumnBuilder,
  ColumnClearExpand,
  ColumnSpanCheck,
  ColumnStretch,
  ColumnWeights,
  CombinationTarget,
  CommuteHunt,
  ComplementLanding,
  CompositionExplorer,
  ConsistencyHunt,
  ConsistencyLine,
  CoordinateBuilder,
  CoordinateFinder,
  CornerToOrigin,
  CostCompare,
  CounterexampleHunt,
  CramerAreas,
  CramerParameterLines,
  CrushAndMiss,
  DerivativeRoutes,
  DerivativeTarget,
  DeterminantSlider,
  DiagonalBasisHunt,
  DiagonalEntryMatch,
  DiagonalFactorSteps,
  DiagonalZeroHunt,
  DifferenceExplorer,
  DifferenceInKernel,
  DotShadowHunt,
  EigenCandidatePicker,
  EigenColumnHunt,
  EigenCoordinateTarget,
  EigenDirectionHunt,
  EigenDirectionSweep,
  EigenGapHunt,
  EigenLineCollapse,
  EigenOrbitSettle,
  EigenPolynomialHunt,
  EigenWeightSplit,
  EigenpairHunt,
  ElementaryMoves,
  EllipseAreaStretch,
  EntryHunt,
  EqualDistanceTurn,
  EvaluationKernel,
  EvaluationZeros,
  FreeWeights,
  GridWeights,
  GrowTheSpan,
  HeightStack,
  ImagePredictor,
  InverseBuilder,
  InverseColumnsHunt,
  InvertibilityCalls,
  IterateSwing,
  JordanChainBuilder,
  LUBuilder,
  LandingHunt,
  LandingPredict,
  LevelPointHunt,
  LiftToPlane,
  LineFootHunt,
  LineOnlyShadow,
  LineSpanPicker,
  LongestStretchHunt,
  LoopAnywhere,
  MatrixVectorExplorer,
  MultipleAreaScale,
  MultiplicityGapSlider,
  NearestPlanePoint,
  NegativeDirectionHunt,
  NegativeFinder,
  NormalizePair,
  NullPowerClimb,
  NullSumCheck,
  OrthogonalWeights,
  OutputReach,
  ParabolaFit,
  PerpendicularPairHunt,
  PivotBudget,
  PivotFlattener,
  PivotHunt,
  PivotPicker,
  PivotSpotter,
  PolynomialCombiner,
  PolynomialCoordinates,
  PolynomialRecipe,
  PolynomialSetTest,
  PowerLineStretch,
  PreimageHunt,
  ProductAreaHunt,
  ProductColumns,
  ProjectionRightAngle,
  QrWeightSliders,
  QuadrantEscape,
  QuadraticAxisTurner,
  QuadraticCircleMax,
  QuadraticSurfaceShaper,
  RangeCollapse,
  RangeProbe,
  RankCopyBudget,
  RankTally,
  RelationFinder,
  RelationTwins,
  RenameTheArrow,
  RepeatedRootSlider,
  ReplacementShear,
  ResidualBalance,
  ResidualSquaresFit,
  RightSideShift,
  RotationColumns,
  RotationDial,
  RowColumnDrop,
  RowLinesMeet,
  RowPerpendicularHunt,
  RowPictureSolver,
  RowRecipe,
  RowReduceExplorer,
  RowReducer,
  RowSlide,
  SameLanding,
  ScaleExplorer,
  ScalingEscape,
  SecondDerivativeTwins,
  ShadowPreimageHunt,
  ShadowStretchSum,
  ShadowSubtractSlider,
  ShadowSumBasis,
  ShapeMatch,
  SharedDerivativeHunt,
  ShearRaySweep,
  ShiftToSingular,
  ShiftedLineTest,
  SignSweep,
  SimilarityHunt,
  SingularHunt,
  SolutionCountExplorer,
  SpanBreaker,
  SpanDimension,
  SpanPainter,
  SpareRecipe,
  SpectralEllipseBuilder,
  StaircaseBasis,
  StatementBoard,
  StraightenedTargetHunt,
  SubstitutionSolver,
  SvdEllipseMatch,
  SymmetricPerpendicularHunt,
  ThirdColumnBudget,
  ThirdPivotSlider,
  ThirdVectorHunt,
  TraceCurveMatch,
  TransformExplorer,
  TranslationGap,
  TriangularPolyMatch,
  TrimToBasis,
  TwoAddresses,
  TwoCoordinateMap,
  TwoTriangleSolve,
  UndoOrder,
  UnitCircleScale,
  VanishingStepHunt,
  VectorExplorer,
  ZeroFunctionHunt,
  ZeroLanding,
  ZeroProductHunt,
};
